export DB_USERNAME=amipatil
export DB_PASSWORD=asdf1234
export PERSISTENCE_UNIT_NAME=my-pu
export SPRING_PROFILES_ACTIVE=dev

echo '--------- Evnrionments ----------'
echo DB_USERNAME=$DB_USERNAME
echo DB_PASSWORD=$DB_PASSWORD
echo PERSISTENCE_UNIT_NAME=$PERSISTENCE_UNIT_NAME
echo SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE